### ISSUE TITLE
Research available APIs there are for accessing browser history

### ISSUE THREAD

**Issue by LazySamir** [LazySamir/googley-eyes#3]

**Comment by DaveLawes** [comment]
- No data stored natively by Chrome for duration of sites visited
- Only exception to this is if a user clicks a link on the loaded page --> not sufficient for us to meet the URL
- We have found that the browser allows JS API calls to access browser-related information, which may be useful for setting our event listeners & event handlers...

Conclusion: closing this issue as we believe the way forward is to create our own data from our extension, not collect existing data by an API

(see wiki)
